### ISSUE TITLE
[共通] ヘッダー フッター カンプ作成

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/hello-worker#15]

**Comment by takashi0602** [comment]
ヘッダー
![s__208994321](https://user-images.githubusercontent.com/30039352/33238674-aba82c16-d2d5-11e7-8bb9-edf437de8b9d.jpg)

***
フッター
![s__208994322](https://user-images.githubusercontent.com/30039352/33238676-adefa206-d2d5-11e7-84c4-4fc99e48e6a6.jpg)

**Comment by tyokinuhata** [comment]
ヘッダーのhello, workerの文字の右横に勤怠管理なら[勤怠管理]、管理画面なら[管理画面]って明示するようにしよか

**Comment by takashi0602** [comment]
![s__212123651](https://user-images.githubusercontent.com/30039352/34333725-0f24db90-e983-11e7-9720-814a607e5199.jpg)

**Comment by tyokinuhata** [comment]
[管理者] -> [管理画面] に文言修正(トップページのリンクが管理画面という文言のため)

確認だけど初期っていうのはサインイン画面での表示ってこと？
トップ画面ではヘッダー出さないので

**Comment by takashi0602** [comment]
![s__212140035](https://user-images.githubusercontent.com/30039352/34339858-80d5fe10-e9bd-11e7-8c5e-e93c7b3c798e.jpg)

**Comment by tyokinuhata** [comment]
すまん、従業員追加か管理者追加かはフォームのチェックボックスで選択させるようにするから、単純に従業員追加と管理者追加を統合してユーザ追加にしてほしい

**Comment by takashi0602** [comment]
![s__212418574](https://user-images.githubusercontent.com/30039352/34440100-321e2d9c-ecf6-11e7-9003-658b87c91faf.jpg)

**Comment by tyokinuhata** [comment]
完成

**Comment by tyokinuhata** [comment]
設定ページヘのリンクをお願いします

**Comment by takashi0602** [comment]
![s__212426759](https://user-images.githubusercontent.com/30039352/34441273-edcdd0e0-ecfd-11e7-933e-2af021715d76.jpg)

**Comment by tyokinuhata** [comment]
あ、ごめん
サインアウトの右にしてほしい

**Comment by takashi0602** [comment]
![s__212467715](https://user-images.githubusercontent.com/30039352/34455463-1840990a-edc3-11e7-90fe-629e08af670c.jpg)

**Comment by tyokinuhata** [comment]
完成
