### ISSUE TITLE
[勤怠管理] 出勤退勤記録ページ＋モーダル

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/hello-worker#17]
![s__212115460](https://user-images.githubusercontent.com/30039352/34333687-bc0eceb6-e982-11e7-999e-63ab35f08a5d.jpg)

***
![s__211976196](https://user-images.githubusercontent.com/30039352/34324588-cea76ec4-e8bb-11e7-9ac8-0fe783d33fe6.jpg)

**Comment by tyokinuhata** [comment]
出勤時間を記録してよろしいですか？ -> 出勤しますか？
退勤時間を記録してよろしいですか？ -> 退勤しますか？
休憩時間を記録してよろしいですか？ -> 休憩しますか？
再開時間を記録してよろしいですか？ -> 再開しますか？
（１つ前の動作）を取り消してもよろしいですか？ -> 現在記録中の出勤を取り消しますか？
これらの文言を修正

OKとキャンセルのボタンの配置を逆にする

というか休憩って記録じゃなくて一時停止だよね？

**Comment by takashi0602** [comment]
![s__212140036](https://user-images.githubusercontent.com/30039352/34339880-bdd76704-e9bd-11e7-84ee-fc2a41ce68f8.jpg)
***
![s__212140037](https://user-images.githubusercontent.com/30039352/34339881-bf0e10fa-e9bd-11e7-80dc-2d73700ec4c9.jpg)

**Comment by tyokinuhata** [comment]
一時停止しますか？ -> 休憩しますか？
再開しますか？ -> 作業を再開しますか？

に変更お願い

**Comment by takashi0602** [comment]
![s__212418575](https://user-images.githubusercontent.com/30039352/34440115-4ad39192-ecf6-11e7-906d-d52a6f491fc7.jpg)

**Comment by tyokinuhata** [comment]
完成
