### ISSUE TITLE
[管理画面] 管理者画面トップ

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/hello-worker#20]
![s__212115461](https://user-images.githubusercontent.com/30039352/34333759-61360ddc-e983-11e7-88f5-adc874dbe0f3.jpg)

**Comment by tyokinuhata** [comment]
セレクトボックスを年と月、ユーザを選択できるように変更
そしてその横に検索ボタンを配置
検索結果に合わせて１番下に合計金額とか合計出勤時間とかもでるように変更

**Comment by takashi0602** [comment]
![s__212140040](https://user-images.githubusercontent.com/30039352/34339910-0f77aa7e-e9be-11e7-8b31-7333ecddd092.jpg)

**Comment by tyokinuhata** [comment]
合計出勤日数/合計出勤時間/合計金額だけでなく、勤怠管理 > 給与明細と同じようにその従業員の明細も表示させるように変更お願い

ページネーションも追加で

**Comment by takashi0602** [comment]
追加フォームの「+, -」は行を追加したり行を減らしたりできる（flsがこんな感じやった気がするので参考にしてみた）
![s__212418577](https://user-images.githubusercontent.com/30039352/34440149-7dfb648c-ecf6-11e7-910a-4e219915dca4.jpg)

**Comment by tyokinuhata** [comment]
行を追加/削除の選択ができるのに「追加」っていうボタンの文言はおかしいかも

そこだけ修正おねがいします

**Comment by takashi0602** [comment]
![s__212418581](https://user-images.githubusercontent.com/30039352/34440590-6a27a0f8-ecf9-11e7-9e20-ed01d52f1d6a.jpg)

**Comment by tyokinuhata** [comment]
完成
