### ISSUE TITLE
[管理画面] 従業員追加

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/hello-worker#24]
![s__212115462](https://user-images.githubusercontent.com/30039352/34333745-3c5c7622-e983-11e7-8680-f163c71d3429.jpg)

**Comment by tyokinuhata** [comment]
交通費の項目と戻るボタンを削除
名前とuser id、メールアドレスを入力フォームの項目とする。

**Comment by takashi0602** [comment]
![s__212140038](https://user-images.githubusercontent.com/30039352/34339891-dde8a454-e9bd-11e7-9c44-00a6001501b4.jpg)

**Comment by tyokinuhata** [comment]
#32 に統合されたためcloseします
