### ISSUE TITLE
[管理画面] 管理者作成

### ISSUE THREAD

**Issue by takashi0602** [tyokinuhata/hello-worker#28]
![s__212115466](https://user-images.githubusercontent.com/30039352/34333774-83e334e0-e983-11e7-8934-d8bbeff64cef.jpg)

**Comment by tyokinuhata** [comment]
- 管理者名
- user id
- メールアドレス
- パスワード

を入力項目とする

戻るボタンは削除する

**Comment by takashi0602** [comment]
![s__212140039](https://user-images.githubusercontent.com/30039352/34339897-f33541b4-e9bd-11e7-8770-d7bae52130ad.jpg)

**Comment by tyokinuhata** [comment]
#32 に統合されたためcloseします
