### ISSUE TITLE
[管理画面] ユーザ追加 カンプ

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/hello-worker#32]
#24 と #28 を統合

従業員名/管理者名 -> ユーザ名 に文言修正

ラジオボタンで従業員/管理者を選択できるように

**Comment by takashi0602** [comment]
![s__212418582](https://user-images.githubusercontent.com/30039352/34440649-d360f4d4-ecf9-11e7-9070-bb0461d91462.jpg)

**Comment by tyokinuhata** [comment]
従業員か管理者かのチェックボックスは一番下にしようかなあ、見栄え的に...

**Comment by takashi0602** [comment]
![s__212418583](https://user-images.githubusercontent.com/30039352/34440840-4909fff4-ecfb-11e7-80c5-8e6c1a651f54.jpg)

**Comment by tyokinuhata** [comment]
完成
