### ISSUE TITLE
[勤怠管理] トップページ カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/hello-worker#6]

**Comment by takashi0602** [comment]
![s__211992578](https://user-images.githubusercontent.com/30039352/34324885-7e57570a-e8c4-11e7-8701-2e8d109f17e2.jpg)

**Comment by tyokinuhata** [comment]
hello, workerはあくまで社内とかで使うことを前提にしてたからキャッチコピーはいらんかなあ

代わりにロゴ入れよう
