### ISSUE TITLE
[勤怠管理] ユーザー登録ページ/ログインページ カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/hello-worker#7]

**Comment by takashi0602** [comment]
![s__211976197](https://user-images.githubusercontent.com/30039352/34324594-0323b4e6-e8bc-11e7-8db4-930c3da0156b.jpg)
![s__211976198](https://user-images.githubusercontent.com/30039352/34324595-0349fd2c-e8bc-11e7-9f21-7aa8c6516c78.jpg)

**Comment by tyokinuhata** [comment]
Laravelデフォルトの登録/ログインをほぼ流用する形にするのでこのカンプでOK

確認したらcloseよろしく

**Comment by tyokinuhata** [comment]
サインアップ画面を削除（管理者が付与するため）

**Comment by tyokinuhata** [comment]
完成
