### ISSUE TITLE
[勤怠管理] ユーザーページ(給与明細) カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [tyokinuhata/hello-worker#8]

**Comment by takashi0602** [comment]
![s__211976200](https://user-images.githubusercontent.com/30039352/34324631-41c66a44-e8bd-11e7-92d1-fb73caa39669.jpg)

**Comment by tyokinuhata** [comment]
マイページはそういう情報もだけど自分の給与明細を見れるようにしてほしいっす

**Comment by takashi0602** [comment]
- 名前
- 仕事先 selectboxで選択
- 勤怠管理
- 給与明細

**Comment by tyokinuhata** [comment]
会社名の選択はないので、20XX年を選択するセレクトボックスとXX月を選択するセレクトボックスにしようか

出勤日数、リモート日数とかはテーブル形式でおねします

**Comment by takashi0602** [comment]
![s__212140041](https://user-images.githubusercontent.com/30039352/34339925-4819a97c-e9be-11e7-955f-1dfb05e264a9.jpg)

**Comment by tyokinuhata** [comment]
セレクトボックスやめてinput type="date"にするか

フォームの横に検索ボタン的なものを設置お願いします

それと検索結果の各行に編集ボタンと削除ボタンを設置。

編集ボタンが押された場合別ページに飛ばすようにするのでページ増えるかもです

あと検索結果が40件以上くらいならページネーションつけたいのでそれもお願い

**Comment by takashi0602** [comment]
![s__212418576](https://user-images.githubusercontent.com/30039352/34440131-612a064c-ecf6-11e7-8963-5fde5ab60e94.jpg)

**Comment by tyokinuhata** [comment]
完成
